pipeline:
  build-and-push:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME%%-service}"
      tags: "${CI_COMMIT_SHA}"
    secrets: [docker_username, docker_password]
when:
  event: push
  branch: master
